const API_ROOT = 'http://localhost:8080/api';

export const API_URLS = {
	register: () => `${API_ROOT}/users/register`,
	login: () => `${API_ROOT}/users/login`,
	createCategory: () => `${API_ROOT}/categories`,
	fetchAllCategories: () => `${API_ROOT}/categories`,
	updateCategory: (id) => `${API_ROOT}/categories/${id}`,
	deleteCategory: (id) => `${API_ROOT}/categories/${id}`,
	fetchCategory: (id) => `${API_ROOT}/categories/${id}`,
	createPost: () => `${API_ROOT}/posts`,
	fetchAllPosts: (category) => `${API_ROOT}/posts?category=${category}`,
	toggleLike: () => `${API_ROOT}/posts/likes`,
	toggleDislike: () => `${API_ROOT}/posts/dislikes`,
	fetchPost: (postId) => `${API_ROOT}/posts/${postId}`,
	updatePost: (postId) => `${API_ROOT}/posts/${postId}`,
	deletePost: (postId) => `${API_ROOT}/posts/${postId}`,
	createComment: () => `${API_ROOT}/comments`,
	deleteComment: (commentId) => `${API_ROOT}/comments/${commentId}`,
	updateComment: (commentId) => `${API_ROOT}/comments/${commentId}`,
	fetchProfile: (userId) => `${API_ROOT}/users/profile/${userId}`,
	updateProfilePhoto: () => `${API_ROOT}/users/profilephoto-upload`,
	updateProfile: () => `${API_ROOT}/users`,
	followUser: () => `${API_ROOT}/users/follow`,
	unFollowUser: () => `${API_ROOT}/users/unfollow`,
	sendEmail: () => `${API_ROOT}/sendEmail`,
	sendVerificationToken: () => `${API_ROOT}/users/generate-verify-email-token`,
	verfifyToken: () => `${API_ROOT}/users/verfiy-account`,
	fetchAllUsers: () => `${API_ROOT}/users/`,
	blockUser: (id) => `${API_ROOT}/users/block-user/${id}`,
	unBlockUser: (id) => `${API_ROOT}/users/unblock-user/${id}`,
};
